name: spkdfs-node

on:
  workflow_dispatch:
   inputs:
      tag:
        description: 'docker image tag'
        required: true
        default: 'latest'
  push:
    branches:
      - master
      - dev
      - feature/docker

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Aliyun Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfiles/Dockerfile.node
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.ALIYUN_REGISTRY }}/little_bee/spkdfs_node:${{ github.event.inputs.tag || 'latest' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
